[package]
name = "simple-bft"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "^0.10"
ed25519-dalek = { version = "2.0.1", features = ["rand_core"] }
rand = "0.8.0"
tokio = { version = "1.44", features = ["full"] }